stages:
  - build
  - deploy-staging
  - deploy-prod

# New stage for building Angular app
build_staging:
  stage: build
  image: trion/ng-cli
  allow_failure: false
  script:
    - npm install
    - npm run build --prod

deploy_staging:
  stage: deploy-staging
  image: ruby:latest
  when: on_success
  dependencies: 
    - build_staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://$HEROKU_APP_STAGING.herokuapp.com
  only:
    - master

deploy_production:
  stage: deploy-prod
  image: ruby:latest
  dependencies: 
    - build_staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_API_KEY
  only:
    - master
  when:
    manual
  allow_failure: false

