apiVersion: apps/v1
kind: Deployment
metadata:
  name: worthit-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worthit
  template:
    metadata:
      labels:
        app: worthit
    spec:
      containers:
        - name: worthit
          # image: us.gcr.io/worth-it-dev/annonces
          image: marouenslaimia/wi-worthit
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://worthit-mongo-srv:27017/worthit"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: worthit-srv
spec:
  selector:
    app: worthit
  ports:
    - name: worthit
      protocol: TCP
      port: 3000
      targetPort: 3000
