name: tests-annonces

on:
  pull_request:
    paths:
      - 'annonces/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd annonces && npm install && npm run test:ci
